### ISSUE TITLE
Class 'Icinga\Util\Translator' not found

### ISSUE THREAD

**Issue by sjwk** [jjethwa/icinga2#290] opened 2022-09-05 09:30 UTC
Following the latest tag, in the current release I get errors in any of the Icinga Director pages: 
`Uncaught Error: Class 'Icinga\Util\Translator' not found in /usr/local/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Translator.php:20`

I've found [an issue](https://github.com/Icinga/icingaweb2-module-director/issues/2548) on the Icingaweb2-module-director repo for the same error, where icingaweb2 has been updated to 2.11 and which was fixed by updating the incubator module to 0.17 (although I see 0.18 is now released), so hopefully a simple fix as the container has 2.11.1 web but only 0.16 incubator?

**Comment by jjethwa** [comment] 2022-09-05 09:59
Hi @sjwk 

Thanks so much for the issue and appreciate the link to the upstream repo!  I'll try the latest release and see if I can reproduce it locally 👍

**Comment by jjethwa** [comment] 2022-09-05 10:35
Hi @sjwk 

I'm not able to reproduce the issue locally, but I just pushed latest with the incubator update.  Can you test it?  Thanks! 😄

**Comment by sjwk** [comment] 2022-09-05 11:31
Hi @jjethwa 
Thanks for a prompt fix.  That does seem to have solved it, not getting that error any more, and from a quick look not seeing any other glitches or error messages.

**Comment by jjethwa** [comment] 2022-09-05 11:44
Thanks so much, @sjwk 👍   I'll go ahead and close this issue.

**Closed by jjethwa** 2022-09-05 11:44 UTC
